version: "3.3"
services:
   wtl_proxy:
    build: wtl_proxy
    #image: ghcr.io/vspaceone/wiki_to_label_proxy:release
    container_name: wtl_proxy
    user: 1000:1000
    ports:
      - 8985:8985
    restart: unless-stopped
    environment:
        CAB_HOST: "wtl_cab_labelprinter.int.vspace.one"
        CAB_TEMPLATE: "/app/templates/ERT-A038X023-1B-1500_simple.txt"

